create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deletion_requested_at timestamptz
);

alter table public.profiles enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = user_id);

create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.cloud_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision integer not null,
  state jsonb not null,
  meta jsonb not null default '{}'::jsonb,
  imported_guest boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, revision)
);

alter table public.cloud_saves enable row level security;

create policy "cloud_saves_select_own"
  on public.cloud_saves for select
  using (auth.uid() = user_id);

create table if not exists public.leaderboard_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  save_id bigint references public.cloud_saves(id) on delete cascade,
  board text not null default 'depth',
  realm_index integer not null default 0,
  realm_name text not null default '炼气一层',
  best_depth integer not null default 0,
  defeated_bosses integer not null default 0,
  combat_power integer not null default 0,
  score integer not null default 0,
  verified boolean not null default false,
  accepted_at timestamptz not null default now()
);

alter table public.leaderboard_snapshots enable row level security;

create policy "leaderboard_snapshots_public_verified_select"
  on public.leaderboard_snapshots for select
  using (verified = true);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.audit_events enable row level security;

create policy "audit_events_select_own"
  on public.audit_events for select
  using (auth.uid() = user_id);

create index if not exists cloud_saves_user_created_idx
  on public.cloud_saves (user_id, created_at desc);

create index if not exists leaderboard_snapshots_depth_idx
  on public.leaderboard_snapshots (board, verified, score desc, accepted_at asc);

create index if not exists audit_events_user_created_idx
  on public.audit_events (user_id, created_at desc);
